status = warn
name = SparkLog

appender.console.type = Console
appender.console.name = console
appender.console.target = SYSTEM_ERR
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{ISO8601} %p %c: %m%n

rootLogger.level = info
rootLogger.appenderRefs = console
rootLogger.appenderRef.console.ref = console

# להפחית רעש מספריות צד
logger.jetty.name = org.eclipse.jetty
logger.jetty.level = warn
logger.akka.name = akka
logger.akka.level = warn
logger.hive.name = org.apache.hive
logger.hive.level = warn
logger.hadoop.name = org.apache.hadoop
logger.hadoop.level = info
logger.spark.name = org.apache.spark
logger.spark.level = info