# Spark default configurations
spark.master                 spark://spark-master:7077
spark.hadoop.fs.defaultFS    hdfs://namenode:8020
spark.ui.showConsoleProgress false

# History Server – לשמירת היסטוריית ריצות לניתוח ביצועים
spark.eventLog.enabled       true
spark.eventLog.dir           hdfs://namenode:8020/spark-events
spark.history.fs.cleaner.enabled true
spark.history.fs.cleaner.maxAge  7d