networks:
  default:
    external:
      name: mirinet
services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    restart: always
    user: "472"
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana-storage:/var/lib/grafana
    networks:
      - default
volumes:
  grafana-storage: {}
