name: bigdata
channels:
  - conda-forge
dependencies:
  # Python base
  - python=3.10

  # PySpark (תואם Spark 3.5.x)
  - pyspark=3.5.3

  # Data & IO
  - pandas
  - numpy
  - pyarrow=16.*
  - fastparquet
  - dask

  # Machine Learning
  - scikit-learn
  - xgboost
  - lightgbm

  - pip:
      - torch
      - torchvision
      - torchaudio
      - tensorflow==2.15
      - keras

      # Storage / Pipelines
      - hdfs==2.7.0
      - mlflow
      - great_expectations

      # Feature Engineering
      - category_encoders
      - featuretools

      # Explainability
      - shap
      - lime
      - phik
      - wordcloud

      # Hyperparameter Tuning
      - optuna

      # NLP + Embeddings
      - sentence-transformers
      - transformers

      # Auto-EDA
      - pandas-profiling

      # OpenAI / LLM
      - openai>=1.0.0
      - tiktoken
      - python-dotenv

  # Jupyter & Dev
  - jupyterlab
  - ipykernel
  - ipywidgets
  - matplotlib
  - seaborn
  - plotly
  - tqdm
  - ipython
